import { TYesOrNo } from './base.js';
export interface ICardResponse {
    activeIndex: number | null;
    addRows: number;
    beginRow: number;
    blockCnt: number;
    cardCategoryName: string | null;
    cardCategoryNo: number;
    cardName: string;
    cardNo: number;
    chattingSeq: number | null;
    color: string;
    concernSeq: number | null;
    content: string | null;
    dailymallNo: number | null;
    delFilesSeq: number | null;
    discountPrice: number | null;
    discountRate: number | null;
    endDate: string | null;
    endRow: number;
    exposeLocation: string | null;
    goodsImageUrl: string | null;
    goodsName: string;
    goodsPrice: number;
    goodsThemeBrief: string | null;
    goodsThemeDetailSeq: number | null;
    goodsThemeIcon: string | null;
    goodsThemeName: string | null;
    goodsThemeNo: number | null;
    gubun1: string | null;
    gubun2: string | null;
    imageUri: string | null;
    imageUrl: string | null;
    isEditorYn: TYesOrNo | null;
    itemArr: unknown | null;
    lastvalue: string | null;
    likeCnt: number | null;
    likeYn: TYesOrNo | null;
    mainScroll: unknown | null;
    menuType: unknown | null;
    mode: unknown | null;
    nickname: string | null;
    page: number;
    profilePhotoUri: string | null;
    readCount: number;
    refererUrl: string | null;
    regDate: string;
    regDateStr: string | null;
    regGubun: string;
    returnUrl: string | null;
    rippleMemberNo: number | null;
    rippleNo: number | null;
    rows: number;
    schField: unknown | null;
    schString: unknown | null;
    scroll: unknown | null;
    sortOrder: number;
    startDate: string | null;
    subDir: string | null;
    subMenuType: number | null;
    subScroll: number | null;
    targetNo: number | null;
    themeBrief: string | null;
    title: string | null;
    totalBlockCnt: number;
    totalCnt: number;
    totalPageCnt: number;
    totalRippleCount: number | null;
    type: unknown | null;
}
